### ISSUE TITLE
Support for current/stable fluentd versions (more recent that 0.12)?

### ISSUE THREAD

**Issue by brycied00d** [norikra/fluent-plugin-norikra#18]
I noticed the gemspec explicitly states `"fluentd", "< 0.14.0"`, as introduced in a3e8ff39f7631a932ad5d2367eec2ea628a07d1d. 

Has development/support of this plugin ceased? Is this plugin incompatible with newer versions of fluentd?

There's at least one Github issue with a user running fluentd 0.14, but no mention was made of any kind of incompatibility. It seems very odd that support for newer/modern versions of fluentd was retracted without any sort of explanation. I also noticed the `migrate-plugin-version` branch completely deleted the `out_norikra.rb` plugin with a vague commit message "use the norikra container." (Edit: Oops I realize now that what I saw was `out_norikra_filter.rb` deleted; `out_norikra.rb` was not actually deleted. My apologies for any confusion.)

The current state of this plugin is extremely unclear to me. If this plugin doesn't support fluentd 1.0, then it should at least be removed from the docs (https://docs.fluentd.org/how-to-guides/cep-norikra https://github.com/fluent/fluentd-docs-gitbook/blob/1.0/guides/cep-norikra.md)

**Comment by tagomoris** [comment]
I started working to make a newer version for Fluentd v0.14 and v1 but didn't have enough time to complete it at that time... "migrate-plugin-version" is the branch for that task, and it's still on working.

**Comment by brycied00d** [comment]
Thanks for the reply! I may try my hand at updating it... 

Closing issue.
