### ISSUE TITLE
in_norikra does't retry to connect Norikra

### ISSUE THREAD

**Issue by mia-0032** [norikra/fluent-plugin-norikra#6]
Does `in_norikra` have feature retrying to connect Norikra ?

I try to start Norikra after fluentd ran.
But `in_norikra` doesn't fetch events output.

If I start Norikra before fluentd ran, `in_norikra` works properly.

My `fluentd.conf` is below.

```
<source>
  type    norikra
  norikra localhost:26571
  <fetch>
    method     sweep
    tag        field tag_name
    tag_prefix query
    interval   1s
  </fetch>
</source>
```

**Comment by tagomoris** [comment]
Fix this issue and released `v0.2.2`. Thank you for great report!
